apiVersion: apps/v1
kind: deployment
metedata:
  name: devsecops-app
  labels:
    app: devsecops-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: devsecops-app
  template:
    metadata:
      name: devsecops-app
      labels:
        app: devsecops-app
    spec:
      containers:
      - name: devsecops-app
        image: ghcr.io/mmsalmanfaris/devsecops-githubaction-pipeline:sha-ecf3fec1815e60df8782e27cca8c8425c4db0a76
        imagePullPolicy: Always
        ports:
        - containerPort: 80

      # TO pull the image in ec2 instance(bcz the image is in private registry)
      imagePullSecrets:
      - name: github-container-registry

      # Also need to configure the github username and token in the ec2

