apiVersion: apps/v1
kind: deployment
metedata:
  name: devsecops-app
  labels:
    app: devsecops-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: devsecops-app
  template:
    metadata:
      name: devsecops-app
      labels:
        app: devsecops-app
    spec:
      containers:
        - name: devsecops-app
          image: ghcr.io/mmsalmanfaris/devsecops-githubaction-pipeline:sha-1e3eba0
          imagePullPolicy: Always
          ports:
          - containerPort: 80