apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsecops-app
  labels:
    app.kubernetes.io/name: devsecops-app
spec:
  rules:
  - host: devsecops-app.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: devsecops-app
            port: 
              number: 80
